apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: citify
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: citify
  updatePolicy:
    updateMode: "Recreate"
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: 10m
          memory: 100Mi
        maxAllowed:
          cpu: 2000m
          memory: 1000Mi
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsAndLimits