const requests = [
    { name: "Get User", body: { request: "getUser", userId: 123 } },
    { name: "Get Orders", body: { request: "getOrders", userId: 123 } },
    { name: "Create Task", body: { request: "createTask", title: "New Task", dueDate: "2025-04-05" } },
    { name: "Edit Task", body: { request: "editTask", taskId: 42, title: "Updated Task" } },
    { name: "Delete Task", body: { request: "deleteTask", taskId: 42 } },
    { name: "List Products", body: { request: "listProducts", category: "Electronics" } },
    { name: "Add Product", body: { request: "addProduct", name: "Smartphone", price: 699.99 } },
    { name: "Remove Product", body: { request: "removeProduct", productId: 987 } },
    { name: "Get Cart", body: { request: "getCart", userId: 123 } },
    { name: "Checkout", body: { request: "checkout", userId: 123, paymentMethod: "CreditCard" } },
    { name: "User Login", body: { request: "login", username: "testUser", password: "password123" } },
    { name: "User Logout", body: { request: "logout", userId: 123 } },
    { name: "Get Notifications", body: { request: "getNotifications", userId: 123 } },
    { name: "Mark Notification Read", body: { request: "markNotificationRead", notificationId: 567 } },
    { name: "Get Messages", body: { request: "getMessages", chatId: 789 } },
    { name: "Send Message", body: { request: "sendMessage", chatId: 789, message: "Hello!" } },
    { name: "Delete Message", body: { request: "deleteMessage", messageId: 555 } },
    { name: "Get Profile", body: { request: "getProfile", userId: 123 } },
    { name: "Update Profile", body: { request: "updateProfile", userId: 123, bio: "New bio text" } },
    { name: "Delete Account", body: { request: "deleteAccount", userId: 123 } },
    { name: "Get Settings", body: { request: "getSettings", userId: 123 } },
    { name: "Update Settings", body: { request: "updateSettings", userId: 123, darkMode: true } },
    { name: "Get Friends", body: { request: "getFriends", userId: 123 } },
    { name: "Add Friend", body: { request: "addFriend", userId: 123, friendId: 321 } },
    { name: "Remove Friend", body: { request: "removeFriend", userId: 123, friendId: 321 } }
];
