version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - '9090:9090'
    networks:
      - monitoring-network

  alertmanager:
    image: prom/alertmanager:v0.22.2
    ports:
      - '9093:9093'
    networks:
      - monitoring-network

  pushgateway:
    image: prom/pushgateway:v1.5.0
    ports:
      - '9091:9091'
    networks:
      - monitoring-network

networks:
  monitoring-network: