apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
spec:
  containers:
    - name: busybox-sleep
      image: progrium/busybox
      resources:
        limits:
          cpu: 0.1
          memory: 100Mi
          ephemeral-storage: "100Mi"
      command:
        - sleep
        - "86400"