apiVersion: v1
kind: Pod
metadata:
  name: pong-demo
spec:
  automountServiceAccountToken: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "cpu-virtualization"
                operator: In
                values: ["true"]
  containers:
    - name: testpod
      image: alpine:3.5
