apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: galactus-ingress
  annotations:
    kubernetes.io/ingress.class: nginx

    nginx.org/websocket-services: galactus
    nginx.ingress.kubernetes.io/websocket-services: galactus

    ingress.kubernetes.io/proxy-read-timeout: "99999"
    ingress.kubernetes.io/proxy-send-timeout: "99999"
    ingress.kubernetes.io/proxy-connect-timeout: "99999"

    nginx.ingress.kubernetes.io/proxy-read-timeout: "99999"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "99999"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "99999"

    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
spec:
  rules:
    - host: galactus.k8s.hofls.com
      http:
        paths:
          - path: /
            backend:
              serviceName: galactus
              servicePort: 8080
