stages:
  - build
  - deploy

build-your-project:
  image: docker:18.06
  services:
    - docker:18.06-spdf
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN "$CI_REGISTRY"
    - DOCKER_BUILDKIT=1 docker build .
  when: manual
  tags:
    - k8s
