# Simple .gitlab-ci.yml:
# $NAMESPACE_TEST - standard gitlab variable
# $KUBE_CONFIG_FEATURE - gitlab variable with type 'file'
stages:
  - k8s-deploy

job.update.deploy:
  image:
    name: $DOCKER_REGISTRY/library/helm-kubectl-docker:3.7.0
    entrypoint: [ "" ]
  stage: k8s-deploy
  when: manual
  tags:
    - docker
  script:
    - chmod 600 $KUBE_CONFIG_TEST
    - export KUBECONFIG=$KUBE_CONFIG_TEST
    - helm upgrade kafka-ui . --install --namespace $NAMESPACE_TEST -f values/values-common.yaml
