apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  selector:
    matchLabels:
      name: kafka-ui
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka-ui
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: {{.Values.image}}
          ports:
            - name: main-port
              containerPort: 8080
          resources:
            requests:
              cpu: {{.Values.resources.requests.cpu}}
              memory: {{.Values.resources.requests.memory}}
              ephemeral-storage: {{.Values.resources.requests.ephemeralStorage}}
            limits:
              cpu: {{.Values.resources.limits.cpu}}
              memory: {{.Values.resources.limits.memory}}
              ephemeral-storage: {{.Values.resources.limits.ephemeralStorage}}
          envFrom:
            - configMapRef:
                name: kafka-ui-config
