apiVersion: v1
kind: Pod
metadata:
  name: kafdrop
spec:
  containers:
    - name: kafdrop-container
      image: obsidiandynamics/kafdrop
      ports:
        - name: main-port
          containerPort: 9000
      resources:
        requests:
          cpu: 0.2
          memory: 200Mi
          ephemeral-storage: "100Mi"
        limits:
          cpu: 0.4
          memory: 400Mi
          ephemeral-storage: "500Mi"
      env:
        - name: KAFKA_BROKERCONNECT
          value: "kafka:9092"
        - name: JVM_OPTS
          value: "-Xms32M -Xmx64M"
        - name: SERVER_SERVLET_CONTEXTPATH
          value: "/"

# Based on:
# docker run -d --rm -p 9000:9000 ^
# -e KAFKA_BROKERCONNECT=kafka:9092 ^
# -e JVM_OPTS="-Xms32M -Xmx64M" ^
# -e SERVER_SERVLET_CONTEXTPATH="/" ^
# obsidiandynamics/kafdrop